Repository SE-Nex-Tech/Nex.Tech, pull requests merged in 2024-02, with the labels that each got.

#8 Authentication
  .env
  next.config.js
  package-lock.json
  package.json
  postcss.config.cjs
  prisma/migrations/20240119074309_init/migration.sql
  prisma/migrations/20240122203757_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  src/app/(forms)/layout.js
  src/app/(forms)/login/login.module.scss
  src/app/(forms)/login/page.jsx
  src/app/(general)/addatabase/page.jsx
  src/app/(general)/adreport/page.jsx
  src/app/(general)/api/auth/[...nextauth]/route.js
  src/app/(general)/api/route.js
  src/app/(general)/books/page.jsx
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/games/page.jsx
  src/app/(general)/globals.scss
  src/app/(general)/layout.js
  src/app/(general)/page.jsx
  src/app/(general)/page.module.scss
  src/app/(general)/providers/providers.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/qrscanner/page.module.scss
  src/app/ebooks/page.jsx
  src/app/page.jsx
  src/app/qrscanner/page.jsx
  src/components/sideNav/Sidebar.jsx
  src/images/building.jpg
  src/images/logo.png
Labels: enhancement

#13 Seeding and Setup
  README.md
  README1.md
  README2.md
  package.json
Labels: documentation, enhancement

#14 Borrow Form and Receipt draft
  .env
  package-lock.json
  package.json
  prisma/seed.js
  src/_components/header/pageTitles.js
  src/app/(general)/borrowform/borrowform.module.scss
  src/app/(general)/borrowform/page.jsx
  src/data/books.csv
Labels: enhancement, frontend

#19 Fix where redirection to landing page from login causes a runtime error #18
  src/app/(general)/dashboard/page.jsx
Labels: enhancement, fix

#22 intial schema creation
  package-lock.json
  prisma/migrations/20240119074309_init/migration.sql
  prisma/migrations/20240122203757_init/migration.sql
  prisma/migrations/20240218133011_init/migration.sql
  prisma/request_seed.js
  prisma/schema.prisma
  prisma/seed.js
  src/_components/catalogs/books.js
  src/app/(general)/books/[id]/page.jsx
  src/data/boardgames.csv
  src/data/books.csv
  src/data/mock.csv
  src/data/requests.csv
Labels: enhancement, backend

#23 Book transactions
  package-lock.json
  package.json
  src/_components/catalogs/books.js
  src/_components/catalogs/books.module.scss
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/borrowform/[id]/borrowform.module.scss
  src/app/(general)/borrowform/[id]/page.jsx
  src/data/books.csv
Labels: enhancement, backend

#26 Borrowform integration with API
  prisma/schema.prisma
  src/app/(general)/api/borrow/borrow.js
  src/app/(general)/api/borrow/route.js
  src/app/(general)/borrowform/[id]/page.jsx
Labels: enhancement, backend

#25 Database page and CRUD forms
  .env
  prisma/migrations/20240225125857_/migration.sql
  src/_components/buttons/addbutton.jsx
  src/_components/buttons/deletebutton.jsx
  src/_components/buttons/editbutton.jsx
  src/_components/crudforms/add.js
  src/_components/crudforms/archive.js
  src/_components/crudforms/edit.js
  src/_components/header/pageTitles.js
  src/_components/sideNav/Sidebar.jsx
  src/_components/sort/sort.js
  src/_components/tables/table.jsx
  src/_components/tables/table.module.scss
  src/app/(general)/addatabase/page.jsx
  src/app/(general)/api/auth/[...nextauth]/route.js
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/dbpage/database.module.scss
  src/app/(general)/dbpage/page.jsx
Labels: enhancement, frontend

#29 Reports Page
  package-lock.json
  package.json
  prisma/migrations/20240229072110_/migration.sql
  src/_components/charts/PieChart.js
  src/_components/charts/piechart.module.scss
  src/_components/header/pageTitles.js
  src/_components/navigator/navigator.js
  src/_components/navigator/navigator.module.scss
  src/_components/sideNav/Sidebar.jsx
  src/app/(general)/adreport/page.jsx
  src/app/(general)/books/[id]/bookpage.module.scss
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/layout.js
  src/app/(general)/reports/page.jsx
  src/app/(general)/reports/reports.module.scss
  src/data/pie.js
  yarn.lock
Labels: enhancement, frontend

#28 Crud integration
  src/_components/buttons/addbutton.jsx
  src/_components/buttons/deletebutton.jsx
  src/_components/buttons/editbutton.jsx
  src/_components/crudforms/add.js
  src/_components/crudforms/archive.js
  src/_components/crudforms/edit.js
  src/_components/tables/table.jsx
  src/app/(general)/api/db/route.js
  src/app/(general)/dbpage/page.jsx
Labels: enhancement, backend

#30 Borrow Form Functions Update
  .env
  prisma/migrations/20240229115621_init/migration.sql
  prisma/schema.prisma
  src/app/(general)/api/borrow/borrow.js
  src/app/(general)/borrowform/[id]/borrowform.module.scss
  src/app/(general)/borrowform/[id]/page.jsx
Labels: enhancement, backend
