Repository SE-Nex-Tech/Nex.Tech, pull requests merged in 2024-03, with the labels that each got.

#31 Merge test
  prisma/migrations/20240229072110_/migration.sql
  prisma/migrations/20240303134336_init/migration.sql
  src/app/(general)/api/db/route.js
  src/app/(general)/borrowform/[id]/page.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/qrscanner/qrscanner.module.scss
Labels: enhancement, fix

#40 Dashboard Component
  .env
  package.json
  src/_components/dashboard/status.jsx
  src/_components/dashboard/status.module.scss
  src/_components/sideNav/Sidebar.jsx
  src/_components/sideNav/sidebar.module.scss
  src/_components/tables/usedtable.jsx
  src/_components/tables/usedtable.module.scss
  src/app/(forms)/login/page.jsx
  src/app/(general)/dashboard/dashboard.module.scss
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/landing/landing.module.scss
  src/app/(general)/landing/page.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/reports/page.jsx
  yarn.lock
Labels: enhancement, frontend

#41 Route protection
  src/_components/authentication/unauthenticated.jsx
  src/_components/authentication/unauthenticated.module.scss
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/dbpage/page.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/reports/page.jsx
Labels: enhancement, backend, frontend

#42 Reports API integration
  src/_components/charts/PieChart.js
  src/app/(general)/api/reports/route.js
  src/app/(general)/reports/page.jsx
Labels: enhancement, fix, backend, frontend

#49 Request Form and QR Scanner Adjustments
  .env
  prisma/migrations/20240307112003_init/migration.sql
  prisma/schema.prisma
  src/app/(general)/api/borrow/borrow.js
  src/app/(general)/api/db/route.js
  src/app/(general)/borrowform/[id]/page.jsx
  src/app/(general)/qrscanner/facultyFields.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/qrscanner/staffFields.jsx
  src/app/(general)/qrscanner/studentFields.jsx
Labels: enhancement, backend

#51 Signup
  src/app/(forms)/signup/page.jsx
  src/app/(general)/api/signup/route.js
Labels: enhancement, backend

#55 Sort By Feature
  src/_components/sort/sort.js
  src/app/(general)/dbpage/page.jsx
  src/app/(general)/dbpage/sortby.js
Labels: enhancement, fix, backend

#56 Revised Schema
  prisma/migrations/20240307112003_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
Labels: enhancement, backend

#59 Superadmin backend
  prisma/schema.prisma
  prisma/seed.js
  src/_components/superadmin/editmodal.jsx
  src/_components/superadmin/menu.jsx
  src/_components/superadmin/menucrud.jsx
  src/_components/superadmin/tableAdmin.jsx
  src/_components/superadmin/tableAuth.jsx
  src/app/(forms)/signup/page.jsx
  src/app/(general)/api/auth/[...nextauth]/route.js
  src/app/(general)/api/signup/route.js
  src/app/(general)/api/superadmin/authorization/route.js
  src/app/(general)/api/superadmin/data/route.js
  src/app/(general)/api/superadmin/deleteadmin/route.js
  src/app/(general)/api/superadmin/editadmin/route.js
  src/app/(superadmin)/admin/page.jsx
Labels: enhancement, backend
