Repository SE-Nex-Tech/Nex.Tech, pull requests merged in 2024-05, with the labels that each got.

#150 DB Page Update
  src/_components/buttons/addbutton.jsx
  src/app/(general)/dbpage/page.jsx
Labels: frontend

#151 Reports Page Update
  src/_components/charts/BarCharts.js
  src/_components/charts/PieCharts.js
  src/_components/charts/barchart.module.scss
  src/app/(general)/api/reports/route.js
  src/app/(general)/reports/page.jsx
  src/app/(general)/reports/reports.module.scss
Labels: enhancement, backend, frontend

#152 Update toast to Top-Center
  src/app/(forms)/login/login.module.scss
  src/app/(forms)/login/page.jsx
  src/app/(forms)/signup/page.jsx
  src/app/(general)/dbpage/page.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/reports/page.jsx
Labels: enhancement, frontend

#153 Recolor
  src/_components/authentication/unauthenticated.jsx
  src/_components/buttons/addbutton.jsx
  src/_components/buttons/deletebutton.jsx
  src/_components/buttons/editbutton.jsx
  src/_components/crudforms/add.js
  src/_components/crudforms/archive.js
  src/_components/crudforms/edit.js
  src/_components/pagination/pagination.js
  src/_components/tables/tableBooks.jsx
  src/app/(forms)/login/login.module.scss
  src/app/(forms)/login/page.jsx
  src/app/(forms)/reset/page.jsx
  src/app/(forms)/reset/reset.module.scss
  src/app/(forms)/signup/page.jsx
  src/app/(general)/books/[id]/bookpage.module.scss
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/borrowform/[id]/borrowform.module.scss
  src/app/(general)/borrowform/[id]/page.jsx
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/games/[id]/gamepage.module.scss
  src/app/(general)/games/[id]/page.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/reports/page.jsx
Labels: enhancement, frontend

#154 Update tablePassword.jsx
  src/_components/superadmin/tablePassword.jsx
Labels: enhancement, frontend

#156 Reports generation update
  package.json
  src/app/(general)/reports/exportToExcel.js
  src/app/(general)/reports/page.jsx
Labels: enhancement, backend

#157 Changed numerical pagination to icons
  src/_components/pagination/pagination.js
  src/_components/pagination/pagination.module.scss
  src/_components/tables/table.module.scss
  src/_components/tables/tableBooks.jsx
  src/_components/tables/tableGames.jsx
Labels: enhancement, frontend

#158 Recolor v2
  src/app/(forms)/reset/reset.module.scss
  src/app/(forms)/signup/signup.module.scss
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/reports/exportToExcel.js
  src/app/(general)/reports/page.jsx
  src/app/(general)/reports/reports.module.scss
Labels: enhancement, frontend

#159 Unarchive
  src/_components/buttons/unarchivebutton.jsx
  src/_components/crudforms/unarchive.js
  src/_components/tables/tableArchive.jsx
  src/app/(general)/api/archive/books/route.js
  src/app/(general)/api/archive/games/route.js
  src/app/(general)/api/unarchive/books/route.js
  src/app/(general)/api/unarchive/games/route.js
  src/app/(general)/dbpage/page.jsx
Labels: enhancement, backend

#160 fix unarchive buttons
  src/_components/crudforms/unarchive.js
Labels: bug, fix

#163 Pagination Responsiveness
  src/_components/tables/tableArchive.jsx
  src/_components/tables/tableBooks.jsx
  src/_components/tables/tableGames.jsx
  src/app/(general)/dbpage/page.jsx
Labels: fix, frontend
