Repository SE-Nex-Tech/Nex.Tech, pull requests merged in 2024-04, with the labels that each got.

#60 Responsive Catalog
  src/_components/catalogs/books.js
  src/_components/catalogs/books.module.scss
  src/_components/catalogs/booksMobile.js
  src/_components/catalogs/booksmobile.module.scss
  src/_components/pagination/pagination.js
  src/_components/pagination/pagination.module.scss
  src/_components/sideNav/sidebar.module.scss
  src/_components/tables/table.module.scss
  src/app/(general)/books/page.jsx
  src/app/(general)/dashboard/dashboard.module.scss
  src/app/(general)/globals.scss
Labels: enhancement, frontend

#61 Change password feature
  prisma/schema.prisma
  src/_components/superadmin/menupw.jsx
  src/_components/superadmin/tablePassword.jsx
  src/app/(forms)/login/page.jsx
  src/app/(forms)/reset/page.jsx
  src/app/(general)/api/reset/approve/route.js
  src/app/(general)/api/reset/reject/route.js
  src/app/(general)/api/reset/request/route.js
  src/app/(general)/api/superadmin/data/route.js
  src/app/(superadmin)/admin/page.jsx
Labels: enhancement, backend

#62 Superadmin and Admin Login
  src/app/(forms)/login/page.jsx
  src/app/(general)/api/login/route.js
Labels: enhancement, backend

#66 ID Responsiveness
  src/_components/navigator/navigator.module.scss
  src/app/(general)/books/[id]/bookpage.module.scss
  src/app/(general)/books/[id]/page.jsx
Labels: enhancement, frontend

#65 Search bar for Catalogs
  src/_components/catalogs/books.js
Labels: enhancement, frontend

#71 Hashed Password at Superadmin View
  src/app/(general)/api/reset/approve/route.js
  src/app/(general)/api/reset/request/route.js
Labels: fix, backend

#81 QR Scanner and Admin protection
  src/_components/superadmin/header.jsx
  src/app/(general)/qrscanner/page.jsx
  src/app/(superadmin)/admin/page.jsx
Labels: fix, backend, frontend

#82 Add and Edit CRUD Tweaks
  src/_components/crudforms/add.js
  src/_components/crudforms/edit.js
Labels: fix, backend, frontend

#84 "Go Back" Button Redirection
  src/app/(general)/borrowform/[id]/borrowform.module.scss
  src/app/(general)/borrowform/[id]/page.jsx
Labels: fix, frontend

#83 Sign Up Responsiveness
  src/app/(forms)/signup/page.jsx
  src/app/(forms)/signup/signup.module.scss
Labels: enhancement, frontend

#85 Games Catalog
  src/_components/catalogs/games.js
  src/_components/catalogs/games.module.scss
  src/app/(general)/api/games/route.js
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/borrowform/[id]/page.jsx
  src/app/(general)/games/[id]/gamepage.module.scss
  src/app/(general)/games/[id]/page.jsx
  src/app/(general)/games/games.module.scss
  src/app/(general)/games/page.jsx
Labels: enhancement, backend, frontend

#87 Archiving elements
  prisma/schema.prisma
  src/app/(general)/api/books/route.js
  src/app/(general)/api/db/route.js
Labels: bug, fix, backend

#88 Catalogs Search Engine
  src/_components/catalogs/books.js
  src/_components/catalogs/games.js
  src/app/(general)/api/db/route.js
Labels: enhancement, backend

#90 Games integration
  src/_components/crudforms/archive.js
  src/_components/crudforms/edit.js
  src/_components/dashboard/statusGames.jsx
  src/_components/tables/tableBooks.jsx
  src/_components/tables/tableGames.jsx
  src/app/(general)/dashboard/dashboard.module.scss
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/dbpage/page.jsx
Labels: enhancement, frontend

#94 Borrowform responsiveness
  src/app/(general)/borrowform/[id]/borrowform.module.scss
  src/app/(general)/borrowform/[id]/page.jsx
  src/app/(general)/dbpage/page.jsx
Labels: enhancement, frontend

#95 Reports Integration
  src/app/(general)/dashboard/dashboard.module.scss
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/reports/page.jsx
  src/app/(general)/reports/reports.module.scss
Labels: enhancement, frontend

#96 Superadmin route protection
  src/app/(general)/api/superadmin/valid/route.js
  src/app/(superadmin)/admin/page.jsx
Labels: enhancement, backend

#98 update games catalog styling
  prisma/request_seed.js
  src/_components/catalogs/games.js
  src/_components/crudforms/add.js
  src/app/(general)/borrowform/[id]/page.jsx
Labels: frontend

#91 Queue information at catalog view
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/games/[id]/page.jsx
Labels: bug, fix, backend, UI/UX

#103 Bug fixes
  src/_components/dashboard/status.jsx
  src/_components/dashboard/status.module.scss
  src/_components/dashboard/statusGames.jsx
  src/app/(general)/dashboard/page.jsx
Labels: bug, fix, backend, frontend

#109 Auth Enhancement
  src/app/(forms)/login/login.module.scss
  src/app/(forms)/login/page.jsx
  src/app/(forms)/reset/page.jsx
  src/app/(forms)/reset/reset.module.scss
  src/app/(forms)/signup/page.jsx
  src/app/(forms)/signup/signup.module.scss
  src/app/(general)/api/signup/route.js
Labels: enhancement, fix, backend, frontend

#111 Dbpage Updates and Major Bug Fixes
  prisma/schema.prisma
  prisma/seed.js
  src/_components/buttons/addbutton.jsx
  src/_components/buttons/deletebutton.jsx
  src/_components/buttons/editbutton.jsx
  src/_components/crudforms/add.js
  src/_components/crudforms/archive.js
  src/_components/crudforms/edit.js
  src/_components/tables/tableBooks.jsx
  src/_components/tables/tableGames.jsx
  src/app/(general)/api/borrow/borrow.js
  src/app/(general)/api/db/route.js
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/borrowform/[id]/page.jsx
  src/app/(general)/dbpage/page.jsx
  src/app/(general)/games/[id]/page.jsx
  src/app/(general)/reports/page.jsx
  src/app/(general)/reports/tableRows.js
Labels: enhancement, fix, backend

#112 Dashboard Restyling
  src/app/(general)/dashboard/dashboard.module.scss
  src/app/(general)/dashboard/page.jsx
  src/app/(general)/reports/page.jsx
Labels: enhancement, frontend

#113 Sort UI Enhancement
  src/app/(general)/dbpage/page.jsx
Labels: enhancement, fix, frontend

#115 Catalogs Redirection
  src/app/(general)/borrowform/[id]/page.jsx
Labels: fix, backend

#123 Callnum Duplicate Validation
  src/_components/crudforms/add.js
  src/_components/crudforms/edit.js
Labels: fix, backend

#120 Dashboard Enhancement
  .env
  src/_components/sideNav/Sidebar.jsx
  src/app/(general)/landing/landing.module.scss
  src/app/(general)/landing/page.jsx
Labels: enhancement, frontend

#122 QR Scanner fix
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/qrscanner/qrscanner.module.scss
Labels: enhancement, frontend

#124 Catalogs fix
  src/_components/catalogs/books.module.scss
  src/_components/catalogs/games.js
  src/_components/catalogs/games.module.scss
  src/_components/catalogs/gamesMobile.js
  src/app/(general)/books/[id]/bookpage.module.scss
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/games/[id]/gamepage.module.scss
  src/app/(general)/games/[id]/page.jsx
  src/app/(general)/games/page.jsx
Labels: enhancement, fix, frontend

#126 Login Max Attempts
  src/app/(forms)/login/login.module.scss
  src/app/(forms)/login/page.jsx
Labels: fix, backend

#132 Data Privacy Act
  src/app/(general)/borrowform/[id]/borrowform.module.scss
  src/app/(general)/borrowform/[id]/page.jsx
Labels: enhancement, frontend

#133 QR Scanner Label Fix
  src/app/(general)/qrscanner/page.jsx
  src/app/(general)/qrscanner/qrscanner.module.scss
Labels: fix, frontend

#134 User Sidebar Hover
  src/_components/sideNav/Sidebar.jsx
Labels: fix, frontend

#136 LocalStorage Fix
  src/app/(forms)/login/login.module.scss
  src/app/(forms)/login/page.jsx
Labels: fix, backend

#137 Audit
  package.json
  prisma/schema.prisma
  src/app/(general)/api/auth/[...nextauth]/route.js
  src/app/(general)/api/borrow/borrow.js
  src/app/(general)/api/db/route.js
  src/app/(general)/api/reset/approve/route.js
  src/app/(general)/api/reset/reject/route.js
  src/app/(general)/api/reset/request/route.js
  src/app/(general)/api/signup/route.js
  src/app/(general)/api/superadmin/authorization/route.js
  src/app/(general)/api/superadmin/deleteadmin/route.js
  src/app/(general)/api/superadmin/editadmin/route.js
  src/logger/logger.js
Labels: documentation, enhancement

#138 hotfix
  src/app/(general)/api/games/route.js
  src/app/(general)/api/queue/q_funcs.js
  src/app/(general)/dbpage/page.jsx
Labels: bug, fix, backend, frontend

#146 Report PDF Styling
  src/app/(general)/reports/page.jsx
Labels: backend

#147 hotfix
  src/app/(general)/qrscanner/page.jsx
Labels: bug, fix, backend

#149 hotfix
  src/app/(general)/qrscanner/page.jsx
Labels: fix

#148 Error Page for 404
  src/_errors/error.module.scss
  src/_errors/notfound.jsx
  src/app/(forms)/layout.js
  src/app/(general)/books/[id]/page.jsx
  src/app/(general)/games/[id]/page.jsx
Labels: enhancement, frontend
